### PR TITLE
Fix for sheet name containing xml escape sequence

### PR DESCRIPTION
**Pull request by agentjill**
As reported in issue #143 , the following is my approach towards solving this. Kindly look into this

### CODE REVIEW

**Comment by agentjill** [comment]
Another approach is to use `worksheet.set_name(convert_character_reference(&name_value));` instead of explicitly calling quick-xml again.

**Comment by MathNya** [comment]
@agentjill 
Thank you for your consideration.
I think this modification is smart and good.
Please release Draft and we will merge it.

https://github.com/MathNya/umya-spreadsheet/pull/145/files#diff-f0f4f74f345f6f1fa8641d024663826eefc687ba2f3bea48d3415e455f366adfR44

**Comment by agentjill** [comment]
@MathNya thanks for the consideration.

**Comment by MathNya** [comment]
@agentjill 
We will merge them.

**Pull request merged**
