### PR TITLE
Stronger Error Types implementation

### PR DESCRIPTION
**Pull request by agentjill**
@MathNya, Inline with clarification given in #203, i have produced a draft of changes envisaged. The changes are inspired from [`calamine`](https://github.com/tafia/calamine) and [`rust_xlsxwriter`](https://github.com/jmcnamara/rust_xlsxwriter). Kindly review this and share your thoughts.

**Note: This PR as of posting is not completely ironed out and needs tests and help from your side after discussion. Kindly donot merge this PR until I mark it as ready to merge**

### CODE REVIEW

**Comment by MathNya** [comment]
@agentjill 
I have seen the proposed amendment.
There are no points raised. I see no problems.
(I was particularly enchanted with the error.rs, which is nicely put together...)

**Comment by agentjill** [comment]
@MathNya, I have added tests to verify the working of `CellErrorType` proper assignment. I am still skeptical of the lengths around which error needed to propogate using the `String` type. I need your insight and opinion whether this is ok and fits the library.

**Comment by MathNya** [comment]
@agentjill 
Confirmed.
There is currently no rule regarding errors.
Therefore, I am unable to determine what is the correct answer.
I think it would be a good idea to release it with this first, and if there are any requests in the future, we can respond to them as needed.

**Comment by agentjill** [comment]
@MathNya, Thanks for the help. Marking as ready to merge. You can now merge as your wish.
**Usual warning of Breaking changes**

**Comment by MathNya** [comment]
@agentjill 
We have confirmed that there is no problem.
We will merge them.

**Pull request merged**
